name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  github-token:  # id of input
    description: 'github-token'
    required: true
  actions:  # id of input
    description: 'actions'
    required: true
    default:  ''
outputs:
  result: # id of output
    description: 'Random number'
    value: '0'
runs:
  using: composite
  steps:
    - name: Await the completion of node_test
      uses: Codex-/await-local-workflow-run@v1.1.0
      with:
        token: ${{ inputs.github-token }} # The standard action GitHub token should be enough to poll the local workflows.
        workflow: node_test.yml # filename of the workflow you wish to await
        check_name: master # Optional
        timeout_mins: 5 # Default: 15
        poll_interval_ms: 10000 # Default: 15000
        