name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  result: # id of output
    description: 'Random number'
    value: ${{ steps.check-github-token.outputs.result }}
runs:
  using: "composite"
  steps:
    - name: check github token 
      id: check-github-token 
      if: ${{ inputs.who-to-greet == 'echoiitime-javascript' }}
      run: echo "ok"
      shell: bash
    # - name: node test
    #   id: node_test
    #   uses: ./.github/workflows/node_test.yml
    - uses: actions/github-script@v6
      id: hello-world-javascript-action
      with:
          github-token: ${{ secrets.JINA_DEV_BOT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'echoiitime-inc',
              repo: 'hello-world-javascript-action',
              workflow_id: 'node_test.yml',
              ref: 'main'
            })
    - name: Get hello-world-javascript-action the output
      run: echo "The time was ${{ steps.hub-integration.outputs.result }}"
      shell: bash
      
    