name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  finally_status: # id of output
    description: 'Random number'
    value: ${{ steps.check-github-token.outputs.result }}
runs:
  using: "composite"
  steps:
    - name: check github token 
      id: check-github-token 
      if: ${{ inputs.who-to-greet == 'echoiitime-javascript' }}
      run: echo "ok"
      shell: bash
    - name: Checkout
      uses: actions/checkout@v3
    - name: node test
      id: node_test
      uses: ./.github/workflows/node_test.yml
      
    