name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  github-token:  # id of input
    description: 'github-token'
    required: true
  actions:  # id of input
    description: 'actions'
    required: true
    default:  ''
outputs:
  result: # id of output
    description: 'Random number'
    value: '0'
runs:
  using: composite
  steps:
    - name: Dispatch an action and get the run ID
      uses: codex-/return-dispatch@v1
      id: return_dispatch
    - uses: ./.github/actions/baseline-test
    
    
        