name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  github-token:  # id of input
    description: 'github-token'
    required: true
  github-run_id: 
    description: 'github-run_id'
    default: ${{ github.run_id }}
    required: true
  actions:  # id of input
    description: 'actions'
    required: true
    default:  ''
outputs:
  result: # id of output
    description: 'Random number'
    value: '0'
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: echoiitime-inc/hello-world-javascript-action/.github/actions/baseline-test/action.yml@master
      with: 
        node-version: '16.x'
        python-version: '3.7'
        case-path: "success/case1"
    - uses: echoiitime-inc/hello-world-javascript-action/.github/actions/docker-source-combine/action.yml@master
      with: 
        python-version: '3.7'
        